/*
 * AboutDialogo.java
 *
 * TODO: Descripcion
 *
 * Creado en 19 de noviembre de 2006, 19:23
 *
 * Copyright (C) 19 de noviembre de 2006, Protactino
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation version 2 of the License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 */

package es.atareao.alejandria.gui;

import java.awt.Desktop;
import java.awt.Dimension;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.JDialog;
import javax.swing.JFrame;
//
//********************************IMPORTACIONES*********************************
//

/**
 *
 * @author  Protactino
 */
public class AboutDialogo extends JDialog {
    //
    //********************************CONSTANTES********************************
    //
    /** Dialog Dimension */
    private final static Dimension _dimension=new Dimension(700,500);
    /** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;
    
    //
    //******************************CONSTRUCTORES*******************************
    //
    /** Creates new form AboutDialogo */
    public AboutDialogo(JFrame padre, boolean modal){
        super(padre,modal);
        initComponents();
        this.setSize(_dimension);
        this.setLocationRelativeTo(null);
        String text="This program is free software: you can redistribute it and/or " +
        "modify it under the terms of the GNU General Public License as published by the " +
        "Free Software Foundation, either version 3 of the License, or any " +
        "later version.\n\n" + 
        "This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; " +
        "without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  " +
        "See the GNU General Public License for more details.\n\n"+
        "You should have received a copy of the GNU General Public License along with this program.  " +
        "If not, see <http://www.gnu.org/licenses/>.\n\n" + 
        "------------------------------------------------------------------------------------------------------------------------\n\n" +
        "Este programa es software libre: usted puede redistribuirlo y/o modificarlo bajo los términos " +
        "de la Licencia Pública General GNU publicada por la Fundación para el Software Libre, ya sea la " +
        "versión 3 de la Licencia, o cualquier versión posterior.\n\n" +
        "Este programa se distribuye con la esperanza de que sea útil, pero SIN GARANTÍA ALGUNA; ni " +
        "siquiera la garantía implícita MERCANTIL o de APTITUD PARA UN PROPÓSITO DETERMINADO. " +
        "Consulte los detalles de la Licencia Pública General GNU para obtener una información más " +
        "detallada.\n\n" +
        "Debería haber recibido una copia de la Licencia Pública General GNU junto a este programa. " +
        "En caso contrario, consulte <http://www.gnu.org/licenses/>.";
        this.jTextAreaLicense.setText(text);
        this.jTextAreaHistory.setCaretPosition(0);
        this.jTextAreaLicense.setCaretPosition(0);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jAceptar = new javax.swing.JButton();
        jCancelar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaLicense = new javax.swing.JTextArea();
        jImage1 = new es.atareao.alejandria.gui.JImage();
        jImage2 = new es.atareao.alejandria.gui.JImage();
        jImage3 = new es.atareao.alejandria.gui.JImage();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaHistory = new javax.swing.JTextArea();
        jImage = new es.atareao.alejandria.gui.JImage();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("A cerca de ...");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jAceptar.setFont(new java.awt.Font("Verdana", 0, 12));
        jAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/atareao/alejandria/gui/button_ok.png"))); // NOI18N
        jAceptar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jAceptar.setBorderPainted(false);
        jAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(jAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, 50, 50));

        jCancelar.setFont(new java.awt.Font("Verdana", 0, 12));
        jCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/atareao/alejandria/gui/button_cancel.png"))); // NOI18N
        jCancelar.setBorder(null);
        jCancelar.setBorderPainted(false);
        jCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, 50, 50));

        jTabbedPane1.setFont(new java.awt.Font("Verdana", 0, 12));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12));
        jLabel1.setText("Durandarte R01.00.20061119");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 290, 20));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12));
        jLabel2.setText("Copyright (C) 2.006 - Lorenzo Carbonell");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 290, 20));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12));
        jLabel3.setText("atareao@atareao.es");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 290, 20));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextAreaLicense.setBackground(java.awt.SystemColor.info);
        jTextAreaLicense.setColumns(20);
        jTextAreaLicense.setEditable(false);
        jTextAreaLicense.setFont(new java.awt.Font("Verdana", 0, 12));
        jTextAreaLicense.setLineWrap(true);
        jTextAreaLicense.setRows(5);
        jTextAreaLicense.setText("This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.\n\nThis program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.\n\nYou should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.\n\n------------------------------------------------------------------------------------------------------------------------\n\nEste programa es software libre: usted puede redistribuirlo y/o modificarlo bajo los términos de la Licencia Pública General GNU publicada por la Fundación para el Software Libre, ya sea la versión 3 de la Licencia, o (a su elección) cualquier versión posterior.\n\nEste programa se distribuye con la esperanza de que sea útil, pero SIN GARANTÍA ALGUNA; ni siquiera la garantía implícita MERCANTIL o de APTITUD PARA UN PROPÓSITO DETERMINADO. Consulte los detalles de la Licencia Pública General GNU para obtener una información más detallada.\n\nDebería haber recibido una copia de la Licencia Pública General GNU junto a este programa. En caso contrario, consulte <http://www.gnu.org/licenses/>.");
        jTextAreaLicense.setWrapStyleWord(true);
        jTextAreaLicense.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextAreaLicense.setDisabledTextColor(java.awt.SystemColor.info);
        jScrollPane2.setViewportView(jTextAreaLicense);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 640, 270));

        jImage1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jImage1.setResourceUrl("/es/atareao/alejandria/images/gplv3-88x31.png");
        jImage1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jImage1MouseClicked(evt);
            }
        });
        jPanel1.add(jImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 90, 60));

        jImage2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jImage2.setResourceUrl("/es/atareao/alejandria/images/by-nc-sa.eu.png");
        jImage2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jImage2MouseClicked(evt);
            }
        });
        jPanel1.add(jImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 130, 60));

        jImage3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jImage3.setResourceUrl("/es/atareao/alejandria/images/elatareao.png");
        jImage3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jImage3MouseClicked(evt);
            }
        });
        jImage3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jImage3MouseDragged(evt);
            }
        });
        jPanel1.add(jImage3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 160, 60));

        jTabbedPane1.addTab("Licencia", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextAreaHistory.setBackground(java.awt.SystemColor.info);
        jTextAreaHistory.setColumns(20);
        jTextAreaHistory.setEditable(false);
        jTextAreaHistory.setFont(new java.awt.Font("Verdana", 0, 12));
        jTextAreaHistory.setLineWrap(true);
        jTextAreaHistory.setRows(5);
        jTextAreaHistory.setText("\"Alea iacta est\" - La suerte está echada.\n\nEstas son las versiones en latín y en español de la frase que se suele atribuir a César al decidir incumplir la prohibición de cruzar el río Rubicón con sus legiones, comenzando así la guerra civil que acabaría con la República Romana y crearía el Imperio Romano. El Rubicón marcaba el límite con la Galia, la provincia donde César debía mantener a sus legiones. Al cruzar del río, estaba invadiendo Roma. Se cree que en realidad lo que pronunció fue un verso en griego.\n\n");
        jTextAreaHistory.setWrapStyleWord(true);
        jTextAreaHistory.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextAreaHistory.setDisabledTextColor(java.awt.SystemColor.info);
        jScrollPane1.setViewportView(jTextAreaHistory);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 400, 320));
        jPanel2.add(jImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, 320));

        jTabbedPane1.addTab("A cerca de ...", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 670, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAceptarActionPerformed
        doClose(RET_OK);
    }//GEN-LAST:event_jAceptarActionPerformed
    
    private void jCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelarActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_jCancelarActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void jImage1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jImage1MouseClicked
        try {
            Desktop.getDesktop().browse(new URI("http://www.gnu.org/licenses/gpl.html"));
        } catch (URISyntaxException ex) {
            ErrorDialog.manejaError(ex);
        } catch (IOException ex) {
            ErrorDialog.manejaError(ex);
        }
    }//GEN-LAST:event_jImage1MouseClicked

    private void jImage2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jImage2MouseClicked
        try {
            Desktop.getDesktop().browse(new URI("http://creativecommons.org/licenses/by-nc-sa/3.0/legalcode"));
        } catch (URISyntaxException ex) {
            ErrorDialog.manejaError(ex);
        } catch (IOException ex) {
            ErrorDialog.manejaError(ex);
        }
    }//GEN-LAST:event_jImage2MouseClicked

    private void jImage3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jImage3MouseClicked
        try {
            Desktop.getDesktop().browse(new URI("http://www.atareao.es"));
        } catch (URISyntaxException ex) {
            ErrorDialog.manejaError(ex);
        } catch (IOException ex) {
            ErrorDialog.manejaError(ex);
        }
    }//GEN-LAST:event_jImage3MouseClicked

    private void jImage3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jImage3MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jImage3MouseDragged

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        try {
            Desktop.getDesktop().mail(new URI("mailto", this.jLabel3.getText(), null));
        }
        catch(IOException ioe) {
            ErrorDialog.manejaError(ioe);
        }
        catch(URISyntaxException use) {
            ErrorDialog.manejaError(use);
        }

    }//GEN-LAST:event_jLabel3MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAceptar;
    private javax.swing.JButton jCancelar;
    private es.atareao.alejandria.gui.JImage jImage;
    private es.atareao.alejandria.gui.JImage jImage1;
    private es.atareao.alejandria.gui.JImage jImage2;
    private es.atareao.alejandria.gui.JImage jImage3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextAreaHistory;
    private javax.swing.JTextArea jTextAreaLicense;
    // End of variables declaration//GEN-END:variables
    //
    // *********************************CAMPOS*********************************
    //
    private int _returnStatus = RET_CANCEL;
    private String _imageName="pawssword.png";
    private String _applicationName="Gladius";
    private String _version="01.00.20061203";
    private String _year="2009";
    private String _author="Lorenzo Carbonell";
    private String _email="lorenzo.carbonell.cerezo@gmail.com";
    private String _texto="\"Alea iacta est\" - La suerte esta echada.\nEstas son " +
            "las versiones en latin y en espaÃ±ol de la frase que se suele atribuir a " +
            "Cesar al decidir incumplir la prohibicion de cruzar el rio Rubicon con" +
            " sus legiones, comenzando asi la guerra civil que acabaria con la Republica Romana" +
            " y crearia el Imperio Romano. El Rubicun marcaba el lumite con la" +
            " Galia, la provincia donde Cesar debia mantener a sus legiones. Al" +
            " cruzar del rio, estaba invadiendo Roma. Se cree que en realidad lo" +
            " que pronuncio fue un verso en griego.";
    //
    //********************************METODOS***********************************
    //
    
    //
    //**************************METODOS AUXILIARES******************************
    //
    private void doClose(int retStatus) {
        _returnStatus = retStatus;
        setVisible(false);
        dispose();
    }
    //
    //**************************METODOS DE ACCESO*******************************
    //
    /** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
    public int getReturnStatus() {
        return _returnStatus;
    }

    public String getApplicationName() {
        return _applicationName;
    }

    public String getVersion() {
        return _version;
    }

    public String getYear() {
        return _year;
    }

    public String getAuthor() {
        return _author;
    }

    public String getEmail() {
        return _email;
    }

    public void setApplicationName(String applicationName) {
        this._applicationName = applicationName;
        jLabel1.setText(this.getApplicationName()+" "+this.getVersion());
    }

    public void setVersion(String version) {
        this._version = version;
        jLabel1.setText(this.getApplicationName()+" "+this.getVersion());
    }

    public void setYear(String year) {
        this._year = year;
        jLabel2.setText("Copyright (C) "+this.getYear()+" - "+this.getAuthor());
    }

    public void setAuthor(String author) {
        this._author = author;
        jLabel2.setText("Copyright (C) "+this.getYear()+" - "+this.getAuthor());
    }

    public void setEmail(String email) {
        this._email = email;
        jLabel3.setText(this.getEmail());
    }

    public String getTexto() {
        return _texto;
    }

    public void setTexto(String texto) {
        this._texto = texto;
        this.jTextAreaHistory.setText(texto);
        this.jTextAreaHistory.setCaretPosition(0);
    }

    public String getImageName() {
        return _imageName;
    }

    public void setImage(String imageName) {
        this._imageName = imageName;
        if(imageName!=null){
            this.jImage.setResourceUrl(imageName);
        }
    }
    /*
    public void setImage(Image image){
        if(image!=null){
            this.jImage.setImage(image);
        }
    }
     * 
     */
}
