/*
 * JUCPanel.java
 *
 * Created on 11 de diciembre de 2007, 6:51
 */

package es.atareao.alejandria.gui;

/**
 *
 * @author  Propietario
 */
public class JDoubleLabel extends javax.swing.JPanel {
    
    /** Creates new form JUCPanel */
    public JDoubleLabel() {
        initComponents();
        this.setHText("UC");
        this.setVText("Unidad de coste");
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jVertical = new es.atareao.alejandria.gui.JVerticalPanel();
        jHorizontal = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        setLayout(new java.awt.BorderLayout());

        jVertical.setFont(new java.awt.Font("Tahoma", 0, 12));
        jVertical.setMinimumSize(new java.awt.Dimension(10, 250));
        jVertical.setPreferredSize(new java.awt.Dimension(10, 250));
        jVertical.setText(" Unidad de coste");

        org.jdesktop.layout.GroupLayout jVerticalLayout = new org.jdesktop.layout.GroupLayout(jVertical);
        jVertical.setLayout(jVerticalLayout);
        jVerticalLayout.setHorizontalGroup(
            jVerticalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 28, Short.MAX_VALUE)
        );
        jVerticalLayout.setVerticalGroup(
            jVerticalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 250, Short.MAX_VALUE)
        );

        add(jVertical, java.awt.BorderLayout.NORTH);

        jHorizontal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jHorizontal.setText("UC");
        jHorizontal.setOpaque(true);
        add(jHorizontal, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jHorizontal;
    private es.atareao.alejandria.gui.JVerticalPanel jVertical;
    // End of variables declaration//GEN-END:variables
 private String _hText;
 private String _vText;

    public String getHText() {
        return _hText;
    }

    public void setHText(String hText) {
        this._hText = hText;
        this.jHorizontal.setText(hText);
    }

    public String getVText() {
        return _vText;
    }

    public void setVText(String vText) {
        this._vText = vText;
        this.jVertical.setText(" "+vText);
    }

 
}
