/*
 * JWeekCell.java
 *
 * Created on 22 de agosto de 2007, 8:13
 */

package es.atareao.alejandria.gui;

import java.awt.Component;
import java.util.Date;
import es.atareao.alejandria.lib.DateUtils;
import es.atareao.alejandria.lib.Suceso;

/**
 *
 * @author  Propietario
 */
public class JWeekCell extends javax.swing.JPanel {
    
    /** Creates new form JWeekCell */
    public JWeekCell() {
        initComponents();
    }
    private void ejecutaEvento(java.beans.PropertyChangeEvent evt, int dia){
        if(evt.getPropertyName().equals("selectedDay")){
            this.setSelectedDay(dia);        
        }
        if(evt.getPropertyName().equals("selectedEvent")){
            this.firePropertyChange("selectedEvent",getSelectedEvent(),evt.getNewValue());
            this._selectedEvent = evt.getNewValue();
        }
        if(evt.getPropertyName().equals("selectedDate")){
            this.firePropertyChange("selectedDate",this.getSelectedDate(),evt.getNewValue());
            this.setSelectedDate((Date)evt.getNewValue());
        }
        
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Código Generado  ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabelSemanaNumber = new javax.swing.JLabel();
        jDayCell1 = new es.atareao.alejandria.gui.JDayCell();
        jDayCell2 = new es.atareao.alejandria.gui.JDayCell();
        jDayCell3 = new es.atareao.alejandria.gui.JDayCell();
        jDayCell4 = new es.atareao.alejandria.gui.JDayCell();
        jDayCell5 = new es.atareao.alejandria.gui.JDayCell();
        jDayCell6 = new es.atareao.alejandria.gui.JDayCell();
        jDayCell7 = new es.atareao.alejandria.gui.JDayCell();

        setLayout(new java.awt.GridLayout(1, 0));

        jLabelSemanaNumber.setBackground(new java.awt.Color(231, 238, 236));
        jLabelSemanaNumber.setFont(new java.awt.Font("Tahoma", 1, 10));
        jLabelSemanaNumber.setForeground(new java.awt.Color(63, 125, 145));
        jLabelSemanaNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSemanaNumber.setText(" 1");
        jLabelSemanaNumber.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(63, 125, 145), 1, true));
        jLabelSemanaNumber.setOpaque(true);
        add(jLabelSemanaNumber);

        jDayCell1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(63, 125, 145), 1, true));
        jDayCell1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDayCell1PropertyChange(evt);
            }
        });

        add(jDayCell1);

        jDayCell2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(63, 125, 145), 1, true));
        jDayCell2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDayCell2PropertyChange(evt);
            }
        });

        add(jDayCell2);

        jDayCell3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(63, 125, 145), 1, true));
        jDayCell3.setColorDeFondo(java.awt.Color.white);
        jDayCell3.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDayCell3PropertyChange(evt);
            }
        });

        add(jDayCell3);

        jDayCell4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(63, 125, 145), 1, true));
        jDayCell4.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDayCell4PropertyChange(evt);
            }
        });

        add(jDayCell4);

        jDayCell5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(63, 125, 145), 1, true));
        jDayCell5.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDayCell5PropertyChange(evt);
            }
        });

        add(jDayCell5);

        jDayCell6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(63, 125, 145), 1, true));
        jDayCell6.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDayCell6PropertyChange(evt);
            }
        });

        add(jDayCell6);

        jDayCell7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(63, 125, 145), 1, true));
        jDayCell7.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDayCell7PropertyChange(evt);
            }
        });

        add(jDayCell7);

    }// </editor-fold>//GEN-END:initComponents

    private void jDayCell7PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDayCell7PropertyChange
        this.ejecutaEvento(evt,7);
    }//GEN-LAST:event_jDayCell7PropertyChange

    private void jDayCell6PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDayCell6PropertyChange
        this.ejecutaEvento(evt,6);
    }//GEN-LAST:event_jDayCell6PropertyChange

    private void jDayCell5PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDayCell5PropertyChange
        this.ejecutaEvento(evt,5);
    }//GEN-LAST:event_jDayCell5PropertyChange

    private void jDayCell4PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDayCell4PropertyChange
        this.ejecutaEvento(evt,4);
    }//GEN-LAST:event_jDayCell4PropertyChange

    private void jDayCell3PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDayCell3PropertyChange
        this.ejecutaEvento(evt,3);
    }//GEN-LAST:event_jDayCell3PropertyChange

    private void jDayCell2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDayCell2PropertyChange
        this.ejecutaEvento(evt,2);
    }//GEN-LAST:event_jDayCell2PropertyChange

    private void jDayCell1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDayCell1PropertyChange
        this.ejecutaEvento(evt,1);
    }//GEN-LAST:event_jDayCell1PropertyChange

    private void siSelecciona(int seleccionado){
        this.seleccionaOno(seleccionado,true);
    }
    private void noSelecciona(int seleccionado){
        this.seleccionaOno(seleccionado,false);
    }
    private void seleccionaOno(int seleccionado,boolean selecciona){
        switch (seleccionado){
            case 1:
                    jDayCell1.setSelected(selecciona);
                    break;
            case 2:
                    jDayCell2.setSelected(selecciona);
                    break;
            case 3:
                    jDayCell3.setSelected(selecciona);
                    break;
            case 4:
                    jDayCell4.setSelected(selecciona);
                    break;
            case 5:
                    jDayCell5.setSelected(selecciona);
                    break;
            case 6:
                    jDayCell6.setSelected(selecciona);
                    break;
            case 7:
                    jDayCell7.setSelected(selecciona);
                    break;
        }
    }
    
    public boolean add(Suceso suceso){
        switch(DateUtils.dayOfWeek(suceso.getDate())){
            case 0:
                return this.jDayCell1.add(suceso);
            case 1:
                return this.jDayCell2.add(suceso);
            case 2:
                return this.jDayCell3.add(suceso);
            case 3:
                return this.jDayCell4.add(suceso);
            case 4:
                return this.jDayCell5.add(suceso);
            case 5:
                return this.jDayCell6.add(suceso);
            case 6:
                return this.jDayCell7.add(suceso);
        }
        return false;
    }
    public boolean remove(Suceso suceso){
        switch(DateUtils.dayOfWeek(suceso.getDate())){
            case 0:
                return this.jDayCell1.remove(suceso);
            case 1:
                return this.jDayCell2.remove(suceso);
            case 2:
                return this.jDayCell3.remove(suceso);
            case 3:
                return this.jDayCell4.remove(suceso);
            case 4:
                return this.jDayCell5.remove(suceso);
            case 5:
                return this.jDayCell6.remove(suceso);
            case 6:
                return this.jDayCell7.remove(suceso);
        }
        return false;
    }
    public boolean contains(Suceso suceso){
        switch(DateUtils.dayOfWeek(suceso.getDate())){
            case 0:
                return this.jDayCell1.contains(suceso);
            case 1:
                return this.jDayCell2.contains(suceso);
            case 2:
                return this.jDayCell3.contains(suceso);
            case 3:
                return this.jDayCell4.contains(suceso);
            case 4:
                return this.jDayCell5.contains(suceso);
            case 5:
                return this.jDayCell6.contains(suceso);
            case 6:
                return this.jDayCell7.contains(suceso);
        }
        return false;
    }
    
    // Declaración de varibales -no modificar//GEN-BEGIN:variables
    private es.atareao.alejandria.gui.JDayCell jDayCell1;
    private es.atareao.alejandria.gui.JDayCell jDayCell2;
    private es.atareao.alejandria.gui.JDayCell jDayCell3;
    private es.atareao.alejandria.gui.JDayCell jDayCell4;
    private es.atareao.alejandria.gui.JDayCell jDayCell5;
    private es.atareao.alejandria.gui.JDayCell jDayCell6;
    private es.atareao.alejandria.gui.JDayCell jDayCell7;
    private javax.swing.JLabel jLabelSemanaNumber;
    // Fin de declaración de variables//GEN-END:variables
    private boolean _selected;
    private int _selectedDay;
    private Date _fecha;
    private int _mes;
    private Object _selectedEvent;
    private Date _selectedDate;

    public int getSelectedDay() {
        return _selectedDay;
    }

    public void setSelectedDay(int selectedDay) {
        int oldSelectedDay=this._selectedDay;
        this._selectedDay = selectedDay;
        if(selectedDay>0){
            this.setSelected(true);
        }else{
            this.setSelected(false);
        }
        this.noSelecciona(oldSelectedDay);
    }

    public boolean isSelected() {
        return _selected;
    }

    public void setSelected(boolean selected) {
        if(selected){
            this.firePropertyChange("selectedWeek",this._selected,selected);
        }else{
            this.noSelecciona(this._selectedDay);
            this._selectedDay=0;
        }
        this._selected = selected;
    }

    public Date getFecha() {
        return _fecha;
    }

    public void setFecha(Date fecha) {
        this._fecha = fecha;
        this.jLabelSemanaNumber.setText(Integer.toString(DateUtils.weekOfYear(fecha)));
        this.jDayCell1.setFecha(fecha);
        if(DateUtils.monthOfYear(fecha)!=this.getMes()){
            this.jDayCell1.setOtroMes(true);
        }else{
            this.jDayCell1.setOtroMes(false);
        }
        
        this.jDayCell2.setFecha(DateUtils.addDays(fecha,1));
        if(DateUtils.monthOfYear(DateUtils.addDays(fecha,1))!=this.getMes()){
            this.jDayCell2.setOtroMes(true);
        }else{
            this.jDayCell2.setOtroMes(false);
        }
        
        this.jDayCell3.setFecha(DateUtils.addDays(fecha,2));
        if(DateUtils.monthOfYear(DateUtils.addDays(fecha,2))!=this.getMes()){
            this.jDayCell3.setOtroMes(true);
        }else{
            this.jDayCell3.setOtroMes(false);
        }
        
        this.jDayCell4.setFecha(DateUtils.addDays(fecha,3));
        if(DateUtils.monthOfYear(DateUtils.addDays(fecha,3))!=this.getMes()){
            this.jDayCell4.setOtroMes(true);
        }else{
            this.jDayCell4.setOtroMes(false);
        }
        
        this.jDayCell5.setFecha(DateUtils.addDays(fecha,4));
        if(DateUtils.monthOfYear(DateUtils.addDays(fecha,4))!=this.getMes()){
            this.jDayCell5.setOtroMes(true);
        }else{
            this.jDayCell5.setOtroMes(false);
        }
        
        this.jDayCell6.setFecha(DateUtils.addDays(fecha,5));
        if(DateUtils.monthOfYear(DateUtils.addDays(fecha,5))!=this.getMes()){
            this.jDayCell6.setOtroMes(true);
        }else{
            this.jDayCell6.setOtroMes(false);
        }
        
        this.jDayCell7.setFecha(DateUtils.addDays(fecha,6));
        if(DateUtils.monthOfYear(DateUtils.addDays(fecha,6))!=this.getMes()){
            this.jDayCell7.setOtroMes(true);
        }else{
            this.jDayCell7.setOtroMes(false);
        }
        
    }

    public int getMes() {
        return _mes;
    }

    public void setMes(int mes) {
        this._mes = mes;
    }

    public Object getSelectedEvent() {
        return _selectedEvent;
    }

    public void setSelectedEvent(Object selectedEvent) {
        this.firePropertyChange("selectedEvent",getSelectedEvent(),selectedEvent);
        this._selectedEvent = selectedEvent;
        if(selectedEvent instanceof Suceso){
            Suceso suceso=(Suceso)selectedEvent;
            switch(DateUtils.dayOfWeek(suceso.getDate())){
                case 0:
                    this.jDayCell1.setSelectedEvent(suceso);
                case 1:
                    this.jDayCell2.setSelectedEvent(suceso);
                case 2:
                    this.jDayCell3.setSelectedEvent(suceso);
                case 3:
                    this.jDayCell4.setSelectedEvent(suceso);
                case 4:
                    this.jDayCell5.setSelectedEvent(suceso);
                case 5:
                    this.jDayCell6.setSelectedEvent(suceso);
                case 6:
                    this.jDayCell7.setSelectedEvent(suceso);
            }
        }
    }

    public Date getSelectedDate() {
        return _selectedDate;
    }

    public void setSelectedDate(Date selectedDate) {
        this._selectedDate = selectedDate;
    }
}