/*
 * UserDialog.java
 *
 * Created on 14 de septiembre de 2006, 12:40
 */

package es.atareao.alejandria.gui;

import java.io.UnsupportedEncodingException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import es.atareao.alejandria.lib.Usuario;

/**
 *
 * @author  Protactino
 */
public class UserModifyDialog extends javax.swing.JDialog {
    //
    //********************************CONSTANTES********************************
    //
    /** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;
    //
    //******************************CONSTRUCTORES*******************************
    //
    
    /** Creates new form UserDialog */
    public UserModifyDialog(JFrame parent, boolean modal,String userName) {
        super(parent, modal);
        initComponents();
        this.setSize(490,240);
        this.setLocationRelativeTo(null);
        //
        this.setUserName(userName);
    }
    public UserModifyDialog(String userName) {
        this(new JFrame(),true,userName);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Código Generado  ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPasswordNuevaCheck = new javax.swing.JPasswordField();
        jPasswordNueva = new javax.swing.JPasswordField();
        jPasswordAntigua = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Contrase\u00f1a");
        setResizable(false);
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/prt/gui/button_ok.png")));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 40, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/prt/gui/button_cancel.png")));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 40, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/prt/gui/password.png")));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLabel1.setText("Usuario");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel2.setText("Antigua contrase\u00f1a");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel3.setText("Nueva contrase\u00f1a");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel4.setText("Repetir nueva contrase\u00f1a");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jPanel1.add(jPasswordNuevaCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 160, -1));

        jPanel1.add(jPasswordNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 160, -1));

        jPanel1.add(jPasswordAntigua, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 160, -1));

        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 160, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 340, 130));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
// TODO add your handling code here:
            doClose(RET_CANCEL);
        } catch (Exception ex) {
            ErrorDialog.manejaError(ex,false);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
// TODO add your handling code here:
            doClose(RET_OK);
        } catch (Exception ex) {
            ErrorDialog.manejaError(ex,false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
       private void doClose(int retStatus) throws Exception {
       if(retStatus==RET_CANCEL){
           this.setUserName(null);
           this.setUserPassword(null);
       }else{
           this.setUserName(this.getUserName());
           if(String.valueOf(this.jPasswordNueva.getPassword()).equals(String.valueOf(this.jPasswordNuevaCheck.getPassword()))){
                this.setUserPassword(this.jPasswordNueva.getPassword());
                this.setUserNewPassword1(this.jPasswordNueva.getPassword());
                this.setUserNewPassword2(this.jPasswordNuevaCheck.getPassword());
           }else{
               throw new Exception("Las contraseñas no coinciden");
           }
           
       }
        this.setReturnStatus(retStatus);
        setVisible(false);
        dispose();

    }    
    // Declaración de varibales -no modificar//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordAntigua;
    private javax.swing.JPasswordField jPasswordNueva;
    private javax.swing.JPasswordField jPasswordNuevaCheck;
    private javax.swing.JTextField jTextField1;
    // Fin de declaración de variables//GEN-END:variables
    private String _userName;
    private char[] _userPassword;
    private char[] _userNewPassword1;
    private char[] _userNewPassword2;
    private int _returnStatus = RET_CANCEL;  

    public int getReturnStatus() {
        return _returnStatus;
    }
    
    public void setReturnStatus(int returnStatus) {
        this._returnStatus = returnStatus;
    }

    public String getUserName() {
        this._userName=this.jTextField1.getText();
        return _userName;
    }

    public void setUserName(String userName) {
        this._userName = userName;
        if(userName!=null){
            this.jTextField1.setText(userName);
        }        
    }

    public char[] getUserPassword() {
        this._userPassword=this.jPasswordAntigua.getPassword();
        return _userPassword;
    }

    public void setUserPassword(char[] userPassword) {
        this._userPassword = userPassword;
    }

    public char[] getUserNewPassword1() {
        return _userNewPassword1;
    }

    public void setUserNewPassword1(char[] userNewPassword1) {
        this._userNewPassword1 = userNewPassword1;
    }

    public char[] getUserNewPassword2() {
        return _userNewPassword2;
    }

    public void setUserNewPassword2(char[] userNewPassword2) {
        this._userNewPassword2 = userNewPassword2;
    }
}
