/*
 * UserDialog.java
 *
 * Created on 14 de septiembre de 2006, 12:40
 */

package es.atareao.alejandria.gui;

import java.awt.event.KeyEvent;
import javax.swing.JFrame;

/**
 *
 * @author  Protactino
 */
public class UserDialog extends javax.swing.JDialog {
    //
    //********************************CONSTANTES********************************
    //
    /** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;
    //
    //******************************CONSTRUCTORES*******************************
    //
    /** Creates new form UserDialog
     * Constructor for a new user dialog
     * @param parent the component parent
     * @param modal you can't access the application
     * @param usuarioName the user name
     * @param usuarioPassword the user password
     */
    public UserDialog(JFrame parent, boolean modal,String usuarioName,char[] usuarioPassword) {
        super(parent, modal);
        initComponents();
        this.setSize(460,230);
        this.setLocationRelativeTo(null);
        //
        this.setUsuarioName(usuarioName);
        this.setUsuarioPassword(usuarioPassword);
    }
    public UserDialog(String usuarioName,char[] usuarioPassword) {
        this(new JFrame(),true,usuarioName,usuarioPassword);
    }
    public UserDialog(String usuarioName){
        this(usuarioName,null);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Contraseña");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/atareao/alejandria/gui/button_ok.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 50, 50));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/atareao/alejandria/gui/button_cancel.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 50, 50));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Usuario");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 70, 25));

        jLabel2.setText("Contraseña");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 70, 25));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 190, 25));

        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyReleased(evt);
            }
        });
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 190, 25));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 300, 120));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/atareao/alejandria/gui/password.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
        doClose(RET_CANCEL);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        doClose(RET_OK);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            this.doClose(RET_OK);
        }
    }//GEN-LAST:event_jPasswordField1KeyReleased
   private void doClose(int retStatus) {
       if(retStatus==RET_CANCEL){
           this.setUsuarioName(null);
           this.setUsuarioPassword(null);
       }else{
           this.setUsuarioName(this.getUsuarioName());
           this.setUsuarioPassword(this.jPasswordField1.getPassword().clone());
           this.jPasswordField1.setText("");
       }
        this.setReturnStatus(retStatus);
        setVisible(false);
        dispose();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    private String _usuarioName;
    private char[] _usuarioPassword=null;
    private int _returnStatus = RET_CANCEL;    

    public String getUsuarioName() {
        this._usuarioName=this.jTextField1.getText();
        return _usuarioName;
    }

    public void setUsuarioName(String usuarioName) {
        this._usuarioName = usuarioName;
        if(usuarioName!=null){
            this.jTextField1.setText(usuarioName);
        }
    }

    public char[] getUsuarioPassword() {
        return _usuarioPassword;
    }

    public void setUsuarioPassword(char[] usuarioPassword) {
        this._usuarioPassword = usuarioPassword;
    }

    public int getReturnStatus() {
        return _returnStatus;
    }
    
    public void setReturnStatus(int returnStatus) {
        this._returnStatus = returnStatus;
    }
}
